name: Generate Snake (Cyber Neon)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Neon Snake
        uses: Platane/snk@v3
        with:
          github_user_name: NilupulThisaranga
          outputs: |
            assets/cyber-snake.svg?color_snake=00ffff&color_dots=#0f172a,#00ff9f,#39ff14,#00ffff,#7df9ff
            assets/cyber-snake.gif?color_snake=00ffff&color_dots=#0f172a,#00ff9f,#39ff14,#00ffff,#7df9ff

      - name: Commit Snake Files
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets/cyber-snake.svg assets/cyber-snake.gif"
          message: "update cyber neon snake"
